# Generated by Django 3.1.2 on 2020-11-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201117_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pintrest_url',
            new_name='pinterest_url',
        ),
    ]
